services:
  app:
    build: .
    ports:
      - 3000:3000
      - 8090:8090
      - 8765:8765
    volumes:
      - ./database/pb_data:/app/database/pb_data
    env_file:
      - .env
    restart: always
